<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * AddSecurityHeaders
 *
 * Applied globally to every response. Audit sprint hardening:
 *
 * ISO 27001 A.14.1 / OWASP A05:
 *   - HSTS added (max-age=31536000; includeSubDomains) — required for all HTTPS
 *     deployments. Forces browsers to HTTPS-only; prevents SSL stripping.
 *
 * OWASP A05 / CSP:
 *   - Removed 'unsafe-inline' from script-src. Inline scripts must be externalised
 *     or use a nonce (see views that need updating). 'unsafe-inline' defeats the
 *     entire purpose of CSP by allowing arbitrary JS injection.
 *
 * OWASP A05 / Deprecated:
 *   - Removed X-XSS-Protection (deprecated in all modern browsers; its
 *     mode=block can actually introduce XSS vulnerabilities in IE/Edge ≤18).
 *
 * ISO 27799 §8.2 / PHI Cache:
 *   - Added Cache-Control: no-store for JSON/FHIR API responses. Prevents
 *     sensitive patient data from being cached by proxies or browser history.
 */
class AddSecurityHeaders
{
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        // ── Universal headers ────────────────────────────────────────────────
        $response->headers->set('X-Content-Type-Options', 'nosniff');
        $response->headers->set('X-Frame-Options', 'DENY');
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');
        $response->headers->set('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');

        // HSTS — ISO 27001 A.14.1 / OWASP A05 (was missing)
        // Only meaningful over HTTPS; harmless over HTTP in development.
        $response->headers->set(
            'Strict-Transport-Security',
            'max-age=31536000; includeSubDomains'
        );

        // Remove server fingerprinting headers
        $response->headers->remove('X-Powered-By');
        $response->headers->remove('Server');
        // X-XSS-Protection intentionally NOT set — it is deprecated and
        // can introduce XSS vulnerabilities in IE/Edge ≤18.

        $contentType = $response->headers->get('Content-Type', '');

        // ── HTML responses: strict CSP ────────────────────────────────────────
        if (str_contains($contentType, 'text/html')) {
            $response->headers->set(
                'Content-Security-Policy',
                // 'unsafe-inline' REMOVED from script-src (OWASP A05 violation).
                // Any inline <script> blocks must be moved to external .js files
                // or converted to use a per-request nonce generated by the view layer.
                "default-src 'self'; " .
                "script-src 'self' https://cdn.jsdelivr.net; " .
                "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; " .
                "font-src 'self' https://fonts.gstatic.com; " .
                "img-src 'self' data: https:; " .
                "connect-src 'self'; " .
                "frame-ancestors 'none';"
            );
        }

        // ── JSON / FHIR API responses: prevent PHI caching ───────────────────
        // ISO 27799 §8.2: patient data must not be stored in caches or history.
        // Applies to all JSON API responses — Connect API, FHIR, patient portal.
        if (
            str_contains($contentType, 'application/json') ||
            str_contains($contentType, 'application/fhir+json')
        ) {
            $response->headers->set('Cache-Control', 'no-store, no-cache, must-revalidate, private');
            $response->headers->set('Pragma', 'no-cache');
        }

        return $response;
    }
}
