<?php

namespace App\Enums;

enum MedicalIdErrorCode: string
{
    case INVALID_HEALTH_ID_FORMAT = 'INVALID_HEALTH_ID_FORMAT';
    case INVALID_HEALTH_ID_CHECKSUM = 'INVALID_HEALTH_ID_CHECKSUM';
    case HEALTH_ID_NOT_FOUND = 'HEALTH_ID_NOT_FOUND';
    case HEALTH_ID_SUSPENDED = 'HEALTH_ID_SUSPENDED';
    case HEALTH_ID_DECEASED = 'HEALTH_ID_DECEASED';
    case HEALTH_ID_ENTERED_IN_ERROR = 'HEALTH_ID_ENTERED_IN_ERROR';
    case HEALTH_ID_DUPLICATE_SUSPECTED = 'HEALTH_ID_DUPLICATE_SUSPECTED';
    case QR_TOKEN_INVALID = 'QR_TOKEN_INVALID';
    case QR_TOKEN_EXPIRED = 'QR_TOKEN_EXPIRED';
    case QR_TOKEN_REVOKED = 'QR_TOKEN_REVOKED';
    case CONSENT_REQUIRED = 'CONSENT_REQUIRED';
    case ACCESS_DENIED = 'ACCESS_DENIED';
    case EMERGENCY_REASON_REQUIRED = 'EMERGENCY_REASON_REQUIRED';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED';
}
