<?php

namespace App\Enums;

enum OpesCareErrorCode: string
{
    case AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    case TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    case TOKEN_REVOKED = 'TOKEN_REVOKED';
    case INSUFFICIENT_SCOPE = 'INSUFFICIENT_SCOPE';
    case FACILITY_SUSPENDED = 'FACILITY_SUSPENDED';
    case ORGANIZATION_NOT_VERIFIED = 'ORGANIZATION_NOT_VERIFIED';
    case CONSENT_REQUIRED = 'CONSENT_REQUIRED';
    case CONSENT_EXPIRED = 'CONSENT_EXPIRED';
    case CONSENT_REVOKED = 'CONSENT_REVOKED';
    case PURPOSE_REQUIRED = 'PURPOSE_REQUIRED';
    case PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND';
    case MULTIPLE_PATIENT_MATCHES = 'MULTIPLE_PATIENT_MATCHES';
    case RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED';
    case IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case UNSAFE_STOCK_STATUS = 'UNSAFE_STOCK_STATUS';
    case UNSAFE_BLOOD_STATUS = 'UNSAFE_BLOOD_STATUS';
    case WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID';
    case RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    case SERVER_ERROR = 'SERVER_ERROR';
}
