<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * ApiInvoice — a monthly bill for an integration client's metered API usage
 * (plan base fee + overage). Generated by ApiBillingService, paid via MTN MoMo
 * or Orange Money, and enforced by EnforceApiQuota (overdue -> API blocked).
 */
class ApiInvoice extends Model
{
    protected $fillable = [
        'client_id', 'facility_id', 'plan_key', 'period_start', 'period_end',
        'included_requests', 'used_requests', 'overage_requests',
        'base_amount_xaf', 'overage_amount_xaf', 'total_xaf', 'currency',
        'status', 'issued_at', 'due_at', 'paid_at', 'payment_provider', 'payment_reference',
    ];

    protected $casts = [
        'period_start'       => 'date',
        'period_end'         => 'date',
        'included_requests'  => 'integer',
        'used_requests'      => 'integer',
        'overage_requests'   => 'integer',
        'base_amount_xaf'    => 'integer',
        'overage_amount_xaf' => 'integer',
        'total_xaf'          => 'integer',
        'issued_at'          => 'datetime',
        'due_at'             => 'datetime',
        'paid_at'            => 'datetime',
    ];

    public function isPaid(): bool
    {
        return $this->status === 'paid';
    }

    public function isOverdue(): bool
    {
        return $this->status === 'overdue'
            || ($this->status === 'issued' && $this->due_at && $this->due_at->isPast());
    }

    /** Human invoice number, e.g. API-2026-06-ACMECLIENT. */
    public function number(): string
    {
        return 'API-' . optional($this->period_start)->format('Y-m') . '-' . strtoupper(substr($this->client_id, 0, 10));
    }

    public function markPaid(string $provider, string $reference): void
    {
        $this->update([
            'status'            => 'paid',
            'paid_at'           => now(),
            'payment_provider'  => $provider,
            'payment_reference' => $reference,
        ]);
    }

    public function client(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(IntegrationClient::class, 'client_id', 'client_id');
    }
}
