<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * HealthIdQrToken
 *
 * Stores QR verification tokens generated by QrTokenService.
 *
 * Primary key: `uuid` (UUID string) — the row's canonical identifier.
 * Lookup key:  `lookup_id` (12-char random) — used for fast O(1) token lookup
 *              without exposing the full UUID in the QR payload.
 *
 * Token format: qrx_{lookup_id}_{secret}
 *   - lookup_id → identifies the row (stored plaintext, unique index)
 *   - secret    → verified via Hash::check() against bcrypt token_hash column
 *
 * Primary key note (audit finding):
 *   HasUuids was removed and replaced with an explicit boot() boot that writes
 *   `uuid` from Str::orderedUuid(). HasUuids in Laravel always targets the
 *   column named in $primaryKey; with $primaryKey = 'uuid' it worked correctly,
 *   but combining HasUuids + custom $primaryKey caused confusion and potential
 *   breakage in Model::find() calls that passed an integer expecting the legacy
 *   auto-increment `id` column. The explicit boot() makes intent unambiguous.
 */
class HealthIdQrToken extends Model
{
    use HasFactory;

    protected $table      = 'health_id_qr_tokens';
    protected $primaryKey = 'uuid';
    public    $incrementing = false;
    protected $keyType    = 'string';

    protected $fillable = [
        'patient_id',
        'lookup_id',
        'token_hash',
        'token_type',
        'status',
        'expires_at',
        'revoked_at',
        'last_used_at',
    ];

    protected $hidden = [
        'token_hash', // Never expose the bcrypt hash in API responses
    ];

    protected static function boot(): void
    {
        parent::boot();

        // Auto-generate a time-ordered UUID for `uuid` (the PK) on create.
        // Using orderedUuid() preserves B-tree index locality.
        static::creating(function (self $model): void {
            if (empty($model->uuid)) {
                $model->uuid = (string) Str::orderedUuid();
            }
        });
    }

    protected function casts(): array
    {
        return [
            'expires_at'   => 'datetime',
            'revoked_at'   => 'datetime',
            'last_used_at' => 'datetime',
        ];
    }

    // ── Relationships ─────────────────────────────────────────────────────────

    public function patient()
    {
        return $this->belongsTo(Patient::class, 'patient_id');
    }

    // ── Scopes ────────────────────────────────────────────────────────────────

    /**
     * Only active, non-expired tokens.
     */
    public function scopeActive($query)
    {
        return $query->where('status', 'active')
            ->where(fn ($q) => $q->whereNull('expires_at')->orWhere('expires_at', '>', now()));
    }
}
