<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;

/**
 * SystemHealthSnapshot — Module 12 (Master Admin Control Center)
 *
 * Point-in-time health snapshot of the platform's infrastructure.
 * Generated by the HealthCheckJob on a schedule.
 * Used for the admin system health dashboard.
 */
class SystemHealthSnapshot extends Model
{
    use HasUuids;

    protected $fillable = [
        'status', 'checks', 'failed_jobs_count',
        'webhook_failures_24h', 'api_error_rate_pct',
        'disk_used_pct', 'avg_response_ms', 'snapshot_at',
    ];

    protected $casts = [
        'checks'              => 'array',
        'disk_used_pct'       => 'decimal:2',
        'avg_response_ms'     => 'decimal:2',
        'snapshot_at'         => 'datetime',
    ];

    public function isHealthy(): bool { return $this->status === 'healthy'; }
    public function isDegraded(): bool { return $this->status === 'degraded'; }
    public function isCritical(): bool { return $this->status === 'critical'; }

    public function statusBadgeClass(): string
    {
        return match($this->status) {
            'healthy'     => 'badge badge--success',
            'degraded'    => 'badge badge--warning',
            'critical'    => 'badge badge--danger',
            'maintenance' => 'badge badge--info',
            default       => 'badge badge--neutral',
        };
    }

    public static function latest(): ?self
    {
        return static::orderByDesc('snapshot_at')->first();
    }
}
