<?php

namespace App\Modules\ClinicalDecisionSupport\Services;

use App\Models\ClinicalAlert;
use App\Models\AlertOverride;

/**
 * ClinicalAlertService — Module 20 (Clinical Decision Support / Alerts)
 *
 * Creates and manages clinical alerts generated by rule evaluation.
 *
 * CDSS Safety: Alerts are informational. Clinicians may override with reason.
 * The platform records all overrides for audit purposes.
 */
class ClinicalAlertService
{
    /**
     * Create a ClinicalAlert from a rule evaluation result.
     */
    public function createFromRuleResult(
        string $visitId,
        string $patientId,
        string $facilityId,
        array $alertPayload,
        string $triggeredBy
    ): ClinicalAlert {
        return ClinicalAlert::create([
            'visit_id'       => $visitId,
            'patient_id'     => $patientId,
            'facility_id'    => $facilityId,
            'alert_type'     => $alertPayload['type'],
            'severity'       => $alertPayload['severity'],
            'message'        => $alertPayload['message'],
            'rule_id'        => $alertPayload['rule_id'] ?? null,
            'status'         => 'active',
            'triggered_by'   => $triggeredBy,
            'triggered_at'   => now(),
        ]);
    }

    /**
     * Acknowledge an alert without overriding it.
     */
    public function acknowledge(ClinicalAlert $alert, string $actorId): void
    {
        $alert->update([
            'status'          => 'acknowledged',
            'acknowledged_by' => $actorId,
            'acknowledged_at' => now(),
        ]);
    }

    /**
     * Override a clinical alert with a documented reason.
     * The override is recorded for audit — cannot be silently suppressed.
     */
    public function override(
        ClinicalAlert $alert,
        string $overriddenBy,
        string $reason
    ): AlertOverride {
        $override = AlertOverride::create([
            'clinical_alert_id' => $alert->id,
            'overridden_by'     => $overriddenBy,
            'reason'            => $reason,
            'overridden_at'     => now(),
        ]);

        $alert->update([
            'status'          => 'overridden',
            'acknowledged_by' => $overriddenBy,
            'acknowledged_at' => now(),
        ]);

        return $override;
    }

    /**
     * Get active (unacknowledged) alerts for a visit.
     */
    public function activeAlertsForVisit(string $visitId): \Illuminate\Database\Eloquent\Collection
    {
        return ClinicalAlert::where('visit_id', $visitId)
            ->where('status', 'active')
            ->orderByDesc('triggered_at')
            ->get();
    }

    /**
     * Get critical unresolved alerts for a facility.
     */
    public function criticalAlertsForFacility(string $facilityId): \Illuminate\Database\Eloquent\Collection
    {
        return ClinicalAlert::where('facility_id', $facilityId)
            ->where('severity', 'critical')
            ->where('status', 'active')
            ->orderByDesc('triggered_at')
            ->get();
    }
}
