<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Seeds facility_registry from the official MINSANTE / WHO directory
 * "Annuaire des Formations Sanitaires Publiques du Cameroun" (Janvier 2023),
 * Catégories 5-6-7 section (CSI / CMA — the health-centre tier below district
 * hospitals). Extracted by coordinate-aware table parsing of the source PDF;
 * every row's category, phone and health area were taken from the same
 * table baseline, and any row that could not be aligned with confidence was
 * dropped rather than guessed.
 *
 * Scope note: the source PDF available at extraction time covered the
 * Adamaoua and Centre regions only. The remaining eight regions are NOT in
 * this seeder — they are absent from the source, not omitted by choice.
 *
 * Ownership is 'public' throughout (this is explicitly the *public* facilities
 * annuaire), except entries operated by the military / gendarmerie.
 *
 * Idempotent — safe to run repeatedly. Rows that a facility has already
 * claimed (claimed_facility_id IS NOT NULL) are never modified.
 *
 * @see CameroonFacilityRegistrySeeder for the initial 2026 registry seed.
 */
class MinsanteFosaRegistrySeeder extends Seeder
{
    private const SOURCE = 'minsante_annuaire_2023';

    public function run(): void
    {
        $added = 0;

        foreach ($this->facilities() as $row) {
            $added += $this->insertIfMissing($row);
        }

        $this->command?->info(sprintf(
            'MinsanteFosaRegistrySeeder: %d new rows (%d from this source, %d registry total).',
            $added,
            DB::table('facility_registry')->where('source', self::SOURCE)->count(),
            DB::table('facility_registry')->count(),
        ));
    }

    /**
     * Insert when absent (unique index: name + region + city).
     *
     * On an existing row we only ever fill columns that are still NULL, and
     * only while the row is unclaimed — a facility that has claimed its
     * registry entry owns its own data and must never be overwritten here.
     *
     * @return int 1 when a new row was inserted, 0 otherwise.
     */
    private function insertIfMissing(array $row): int
    {
        $inserted = DB::table('facility_registry')->insertOrIgnore(array_merge($row, [
            'id'         => (string) Str::uuid(),
            'source'     => self::SOURCE,
            'status'     => 'unverified',
            'created_at' => now(),
            'updated_at' => now(),
        ]));

        if ($inserted) {
            return 1;
        }

        // Row already present — backfill only empty columns, never overwrite.
        $fill = [];

        foreach (['phone', 'division', 'address', 'accreditation_level'] as $col) {
            if (! empty($row[$col])) {
                $fill[$col] = $row[$col];
            }
        }

        if ($fill === []) {
            return 0;
        }

        $query = DB::table('facility_registry')
            ->where('name', $row['name'])
            ->where('region', $row['region'])
            ->where('city', $row['city'])
            ->whereNull('claimed_facility_id');

        foreach (array_keys($fill) as $col) {
            $query->whereNull($col);
        }

        // whereNull on every target column means a partially-filled row is
        // left completely alone rather than half-updated.
        $query->update($fill + ['updated_at' => now()]);

        return 0;
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function facilities(): array
    {
        return array_merge(
            $this->adamaoua(),
            $this->centre(),
        );
    }

    /**
     * Adamaoua — 88 facilities (catégories 5/6/7).
     */
    private function adamaoua(): array
    {
        return [
            ['name' => 'CMA Songkolong',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Songkolong', 'phone' => '+237 670 07 71 27'],
            ['name' => 'CSI Atta',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Atta', 'phone' => '+237 653 36 34 30'],
            ['name' => 'CSI Bandam',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bandam', 'phone' => '+237 670 40 14 35'],
            ['name' => 'CSI DIEKI',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Dieki', 'phone' => '+237 670 62 97 58'],
            ['name' => 'CSI Kimi-Petel',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de KIMI-PETEL', 'phone' => '+237 676 59 60 70'],
            ['name' => 'CSI Ngatti',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bankim Rural', 'phone' => '+237 671 63 31 38'],
            ['name' => 'CSI Nyamboya',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nyamboya', 'phone' => '+237 691 25 00 15'],
            ['name' => 'CSI Somie',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Somie', 'phone' => '+237 671 14 28 80'],
            ['name' => 'CSI Tchamba',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bankim',     'city' => 'Bankim',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Tchamba', 'phone' => '+237 677 04 28 72'],
            ['name' => 'CMA Mayo-Darley',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Mayo Darle', 'phone' => '+237 674 21 61 06'],
            ['name' => 'CSI Banyo Fada',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Banyo 1 Fada', 'phone' => '+237 673 68 84 24'],
            ['name' => 'CSI Djem',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 675 47 97 25'],
            ['name' => 'CSI Mayo Kelele',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Sambo Labo', 'phone' => '+237 670 07 63 28'],
            ['name' => 'CSI MbamtiKatarko',                                'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de MbamtiKatarko', 'phone' => '+237 677 07 33 35'],
            ['name' => 'CSI NdiWawa',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de NdiWawa', 'phone' => '+237 675 45 01 79'],
            ['name' => 'CSI Ribao',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 673 79 34 77'],
            ['name' => 'CSI Sambo Labo',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 691 71 67 61'],
            ['name' => 'CSI TaramYabam',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 677 99 59 40'],
            ['name' => 'CSI de Boumdo',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 654 37 15 09'],
            ['name' => 'CSI de Mayo-Djinga',                               'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 677 41 11 01'],
            ['name' => 'CSI de Tiket',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Banyo',      'city' => 'Banyo',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Banyo 2 Tiket', 'phone' => '+237 674 97 85 37'],
            ['name' => 'CMA Bélel',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Bélel', 'phone' => '+237 693 21 85 88'],
            ['name' => 'CMA Idool',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Idool', 'phone' => '+237 675 87 03 16'],
            ['name' => 'CSI Bayara',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bayara', 'phone' => '+237 670 15 53 28'],
            ['name' => 'CSI Djilougou',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Djilpugou', 'phone' => '+237 675 25 36 77'],
            ['name' => 'CSI Goumdjel Pastoral',                            'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Tello', 'phone' => '+237 697 00 43 70'],
            ['name' => 'CSI Tello Public',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 6', 'phone' => '+237 695 96 44 62'],
            ['name' => 'CSI Tourningal',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Bélel',      'city' => 'Bélel',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Tourningal', 'phone' => '+237 693 35 41 25'],
            ['name' => 'CMS Université de Ngaoundéré (CNLS)',              'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 7', 'address' => 'Aire de Santé de Dang', 'phone' => '+237 696 77 15 66'],
            ['name' => 'CSI Hangloa',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Hangloa', 'phone' => '+237 696 89 67 00'],
            ['name' => 'CSI LewaMboum',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de LewaMboum', 'phone' => '+237 677 52 28 78'],
            ['name' => 'CSI Likok',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Likok', 'phone' => '+237 670 26 84 00'],
            ['name' => 'CSI LouggaTappadi',                                'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Martap', 'phone' => '+237 698 22 99 78'],
            ['name' => 'CSI Mandourou',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mandourou', 'phone' => '+237 697 48 44 51'],
            ['name' => 'CSI Martap',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'phone' => '+237 693 68 46 42'],
            ['name' => 'CSI Nganha',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nganha', 'phone' => '+237 670 25 11 57'],
            ['name' => 'CSI Nyassar',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Dang',       'city' => 'Dang',       'accreditation_level' => 'Catégorie 6', 'phone' => '+237 694 31 15 27'],
            ['name' => 'CMA Ngaoui',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Ngaoui', 'phone' => '+237 693 42 00 38'],
            ['name' => 'CSI Alhamdou',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 699 60 23 77'],
            ['name' => 'CSI Bafouck',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 695 34 24 34'],
            ['name' => 'CSI Batouagodole',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Kombolaka', 'phone' => '+237 695 16 06 64'],
            ['name' => 'CSI Borgop',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 699 63 93 15'],
            ['name' => 'CSI Diel',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Djohong', 'phone' => '+237 690 71 88 44'],
            ['name' => 'CSI Djohong',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 693 98 52 66'],
            ['name' => 'CSI Fada',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 699 24 14 78'],
            ['name' => 'CSI Garga Pella',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 690 91 35 60'],
            ['name' => 'CSI Kombo Laka',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 695 16 06 64'],
            ['name' => 'CSI Ngam',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 694 63 30 26'],
            ['name' => 'CSI OuroAdde',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 697 45 66 11'],
            ['name' => 'CSI de Yamba',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Yarmbang', 'phone' => '+237 658 35 82 11'],
            ['name' => 'CSI de Yarmbang',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 690 91 18 58'],
            ['name' => 'PSF Ngaoui',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Djohong',    'city' => 'Djohong',    'accreditation_level' => 'Catégorie 7', 'phone' => '+237 674 12 00 20'],
            ['name' => 'CSI Allat-Mengack',                                'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de AllatMengack', 'phone' => '+237 651 72 47 32'],
            ['name' => 'CSI Djombi',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Djombi', 'phone' => '+237 675 99 04 57'],
            ['name' => 'CSI Lainde Ngoudda',                               'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'phone' => '+237 673 09 11 73'],
            ['name' => 'CSI Liboum',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mbakaou', 'phone' => '+237 681 20 28 70'],
            ['name' => 'CSI Marma',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Tongo (Tibati)', 'phone' => '+237 674 24 55 47'],
            ['name' => 'CSI Mbakaou',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'phone' => '+237 679 38 22 96'],
            ['name' => 'CSI Mbirim',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'phone' => '+237 677 84 46 83'],
            ['name' => 'CSI Meidjamba',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Meidjamba', 'phone' => '+237 670 62 30 39'],
            ['name' => 'CSI Minim',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Minim', 'phone' => '+237 670 67 80 54'],
            ['name' => 'CSI Ngaoubéla',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ngaoubela', 'phone' => '+237 674 11 78 46'],
            ['name' => 'CSI Ngatt Public',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'phone' => '+237 677 17 21 89'],
            ['name' => 'CSI Samba',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'phone' => '+237 678 01 01 50'],
            ['name' => 'CSI Tibati',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Tibati CSI', 'phone' => '+237 677 09 66 43'],
            ['name' => 'CSI Tongo',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 6', 'phone' => '+237 675 36 06 67'],
            ['name' => 'Centre Medical 33e BIM',                           'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 7', 'address' => 'Aire de Santé de Tibati CMA', 'phone' => '+237 675 63 17 75'],
            ['name' => 'Infirmerie Prison Principale de Tibati',           'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tibati',     'city' => 'Tibati',     'accreditation_level' => 'Catégorie 7', 'phone' => '+237 675 37 77 20'],
            ['name' => 'CMA GalimTignere',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de GalimTignere', 'phone' => '+237 695 28 35 45'],
            ['name' => 'CMA Kontcha',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Kontcha', 'phone' => '+237 696 22 40 79'],
            ['name' => 'CMA Mayo Baleo',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Mayo Baleo', 'phone' => '+237 652 87 89 86'],
            ['name' => 'CMADoualayel',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Doualayel', 'phone' => '+237 698 14 74 22'],
            ['name' => 'CSI Alme',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Alme', 'phone' => '+237 675 43 54 43'],
            ['name' => 'CSI De Gassanguel (cnls)',                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Tignere', 'phone' => '+237 680 15 48 16'],
            ['name' => 'CSI Dodeo',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Dodeo', 'phone' => '+237 654 79 48 70'],
            ['name' => 'CSI Gadjiwan',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Gadjiwan', 'phone' => '+237 679 63 14 98'],
            ['name' => 'CSI GarbayaDjire',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de GarbayaYelwa'],
            ['name' => 'CSI Garbayayelwa',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 655 50 58 59'],
            ['name' => 'CSI Kontcha',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 678 25 78 78'],
            ['name' => 'CSI Libong',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Libong', 'phone' => '+237 678 28 64 57'],
            ['name' => 'CSI Lompta',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 674 86 67 84'],
            ['name' => 'CSI Mayo Baleo',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 670 15 69 85'],
            ['name' => 'CSI Mayo Dankali',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 699 92 27 46'],
            ['name' => 'CSI Sadeck',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 650 81 08 64'],
            ['name' => 'CSI TchabalMbabo',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de TchabalMbabo', 'phone' => '+237 674 87 92 08'],
            ['name' => 'CSI Tignere',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 674 41 08 86'],
            ['name' => 'CSI Wogoumdou',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Wogoumdou', 'phone' => '+237 673 73 72 68'],
            ['name' => 'CSI Woulde',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Adamaoua',      'division' => 'District de Santé de Tignere',    'city' => 'Tignere',    'accreditation_level' => 'Catégorie 6', 'phone' => '+237 683 65 80 40'],
        ];
    }

    /**
     * Centre — 170 facilities (catégories 5/6/7).
     */
    private function centre(): array
    {
        return [
            ['name' => 'CMA Endom',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Endom'],
            ['name' => 'CSI Abem',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Abem'],
            ['name' => 'CSI Akak',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Akak'],
            ['name' => 'CSI AkoaLui',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI AndomEboa',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Akonolinga Urbain'],
            ['name' => 'CSI Ate',                                          'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mengueme Si'],
            ['name' => 'CSI Djoudjoua',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Djoudjoua'],
            ['name' => 'CSI Ebolakounou',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mengang'],
            ['name' => 'CSI Eboman',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Edjom'],
            ['name' => 'CSI Edjom',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Edou',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Ekoudou',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ekoudou (Akonolinga)'],
            ['name' => 'CSI EmvaneSso',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de EnvaneSso'],
            ['name' => 'CSI Mefindi',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Mengang',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI MenguemeSsi',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI NDOUNDOU',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de YemeYeme'],
            ['name' => 'CSI NkoZe',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Nlobole',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI YemeYeme',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Zalom',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Zalom'],
            ['name' => 'CSIU Akonolinga',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'Infirmerie Prison - Akonolinga',                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Akonolinga', 'city' => 'Akonolinga', 'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CMA ElatMinkom',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Awae',       'city' => 'Awae',       'accreditation_level' => 'Catégorie 5'],
            ['name' => 'CSI Mimbang',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Awae',       'city' => 'Awae',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mimbang'],
            ['name' => 'CSI Ngat',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Awae',       'city' => 'Awae',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ngat'],
            ['name' => 'CSI Nkolessong',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Awae',       'city' => 'Awae',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nkolessong'],
            ['name' => 'CSI Olanguina',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Awae',       'city' => 'Awae',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Olanguina'],
            ['name' => 'CMA Kobdombo',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Kobdombo'],
            ['name' => 'CSI Ayos Urbain',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ayos Urbain'],
            ['name' => 'CSI Efoufoup',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Efoufoup'],
            ['name' => 'CSI Kombo',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Mang',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mang'],
            ['name' => 'CSI Mbaka',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mbaka (Ayos)'],
            ['name' => 'CSI Mboke',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mboke'],
            ['name' => 'CSI Ndele',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ndellé'],
            ['name' => 'CSI Nganga',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nganga'],
            ['name' => 'CSI Ngombo',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Nkoambang',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nkoambang'],
            ['name' => 'CSI Nnemeyong',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Nyamvoudou',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nyamvoudou'],
            ['name' => 'CSI Salla',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Yenassa',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Yenassa'],
            ['name' => 'CSI de Ngoulkeka',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ayos',       'city' => 'Ayos',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Salla'],
            ['name' => 'CMA Balamba',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Balamba'],
            ['name' => 'CMA Bokito',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Bokito'],
            ['name' => 'CMA Deuk',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 5'],
            ['name' => 'CMA Kiiki',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Kiki'],
            ['name' => 'CMA Kon-Yambeta',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 5'],
            ['name' => 'CSI Abanda',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mouko'],
            ['name' => 'CSI Assala',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Assala'],
            ['name' => 'CSI Bakoa',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Baliama',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Baliama'],
            ['name' => 'CSI Bangong',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Gbwah'],
            ['name' => 'CSI Begui',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bayomen'],
            ['name' => 'CSI Bitang',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Boko Montagne',                                'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Bongo',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bongo'],
            ['name' => 'CSI Essende',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Goufan'],
            ['name' => 'CSI Goufan',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Gouife',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Guefigue',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Guientsing',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI MPAGNE',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Deuk'],
            ['name' => 'CSI Mereng',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bafia rural'],
            ['name' => 'CSI Mouko',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI OSSIMB',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Omende',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Tsekos',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Yambassa',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'INFIMERIE PRISON',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Bafia',      'city' => 'Bafia',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de BAFIA 1'],
            ['name' => 'CM Gendarmerie Nationale',                         'type' => 'health_center', 'ownership' => 'military',   'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Elig Effa'],
            ['name' => 'CM de la Base Militaire',                          'type' => 'health_center', 'ownership' => 'military',   'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 5'],
            ['name' => 'CMA Mendong',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Mendong'],
            ['name' => 'CMA MvogBetsi',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Mvogbetsi'],
            ['name' => 'CNRPH',                                            'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Akok-ndoe'],
            ['name' => 'CSI Simbock',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Simbok'],
            ['name' => 'Centre Medical de la Garde Presidentielle',        'type' => 'health_center', 'ownership' => 'military',   'region' => 'Centre',        'division' => 'District de Santé de Biyem-Assi', 'city' => 'Biyem-Assi', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Biscuiterie'],
            ['name' => 'CMA Tsinga',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Cité Verte', 'city' => 'Cité Verte', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Ekoudou (Cite Verte)'],
            ['name' => 'CSI Briqueterie',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Cité Verte', 'city' => 'Cité Verte', 'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Briqueterie'],
            ['name' => 'CVI Messa',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Cité Verte', 'city' => 'Cité Verte', 'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Messa'],
            ['name' => 'CMA Elig Essono',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Djoungolo',  'city' => 'Djoungolo',  'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Eligessono'],
            ['name' => 'CSI d\'Emana',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Djoungolo',  'city' => 'Djoungolo',  'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Emana'],
            ['name' => 'CSI des Logement Sociaux',                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Djoungolo',  'city' => 'Djoungolo',  'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nkolondom'],
            ['name' => 'Centre de Vaccination de Jamot',                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Djoungolo',  'city' => 'Djoungolo',  'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mballa 2'],
            ['name' => 'SSCNSP / Centre Médical des Sapeurs pompiers',     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Djoungolo',  'city' => 'Djoungolo',  'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Nlongkak'],
            ['name' => 'CSI Endoum',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ebebda',     'city' => 'Ebebda',     'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Leka',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ebebda',     'city' => 'Ebebda',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Leka'],
            ['name' => 'CSI Ngoksa',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ebebda',     'city' => 'Ebebda',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ngoksa'],
            ['name' => 'CSI NkangEfok',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ebebda',     'city' => 'Ebebda',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Djounyat'],
            ['name' => 'CSI Nkolelouga',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ebebda',     'city' => 'Ebebda',     'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nkolelouga'],
            ['name' => 'CSI Nkom 1',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Ebebda',     'city' => 'Ebebda',     'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CMA Ahala',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Ahala 1'],
            ['name' => 'CMA ETOA',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Afanoyoa 1'],
            ['name' => 'CMA Obili',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 5'],
            ['name' => 'CSI Afanoyoa 4',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Afanoyoa 2'],
            ['name' => 'CSI Ntouessong 1',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Obili',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Obili 2'],
            ['name' => 'Centre Medical BQG (Brigade du Quartier General)', 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Efoulan',    'city' => 'Efoulan',    'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Ngoa-Ekelle'],
            ['name' => 'CSI Endama',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Elig-Mfomo'],
            ['name' => 'CSI Kokodo 2',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Kokodo'],
            ['name' => 'CSI KomoEssele',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Mbanedouma',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Niga',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Nkengue',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nkengue'],
            ['name' => 'CSI Nkolossan',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de EligMfomo',  'city' => 'EligMfomo',  'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CMA Bondjock',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Bondjock'],
            ['name' => 'CMA Makak',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Makak'],
            ['name' => 'CMA Messondo',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de Messondo'],
            ['name' => 'CSI BOGSO',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de ILanga'],
            ['name' => 'CSI Bidjocka',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bidjocka'],
            ['name' => 'CSI Biyouha',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Song bayang'],
            ['name' => 'CSI Boumnkok',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Likongue'],
            ['name' => 'CSI Lindoi',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bondjock'],
            ['name' => 'CSI Manguengues',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Eseka'],
            ['name' => 'CSI Mbeng',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mom'],
            ['name' => 'CSI Mbengue',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Messondo'],
            ['name' => 'CSI Mboui',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Mom',                                          'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Mom'],
            ['name' => 'CSI Ndogbessol',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bidjocka'],
            ['name' => 'CSI Nguibassal 2',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Eseka'],
            ['name' => 'CSI Nkongnkeni',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Bondjock'],
            ['name' => 'CSI Song Badjeck',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Song-badjeck'],
            ['name' => 'CSI Song Bayang',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Song bayang'],
            ['name' => 'CSI Song Mbong',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Songmbong'],
            ['name' => 'CSI Urbain Eseka',                                 'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Eseka',      'city' => 'Eseka',      'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Eseka'],
            ['name' => 'CSI Afanetouana',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de NgondiMbele'],
            ['name' => 'CSI Afanloum',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Afanloum'],
            ['name' => 'CSI Ebogo',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Esse ville'],
            ['name' => 'CSI Edzendouan',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Edzendouan'],
            ['name' => 'CSI Fegminbang',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI MENGUEME',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de MvengEssaboutou'],
            ['name' => 'CSI Mbemedzou',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI MvengEssaboutou',                              'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Ndzana',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI NgondiMbele',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Ngoungoumou',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Ngoungoumou'],
            ['name' => 'CSI Nkolmeyo',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Esse',       'city' => 'Esse',       'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI Kalngaha',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Evodoula',   'city' => 'Evodoula',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Kalngaha'],
            ['name' => 'CSI Nkolabang',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Evodoula',   'city' => 'Evodoula',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nloudou'],
            ['name' => 'CSI Nkolassa',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Evodoula',   'city' => 'Evodoula',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Nkolassa'],
            ['name' => 'CSI Nkolkouga',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Evodoula',   'city' => 'Evodoula',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de Evodoula'],
            ['name' => 'CSI Nloudou',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Evodoula',   'city' => 'Evodoula',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CMA NGOMEDZAP',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de NGOMEDZAP'],
            ['name' => 'CMA NKOLYA',                                       'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 5', 'address' => 'Aire de Santé de NKOLYA'],
            ['name' => 'CSI ABOD MVENG',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI ANGONFEME',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de ANGONFEME'],
            ['name' => 'CSI ASSANZOA',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de NGALLAN'],
            ['name' => 'CSI ASSIE',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de ASSIE'],
            ['name' => 'CSI AWAE',                                         'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI BILON',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI EKOUMEYECK',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de EKOUMEYECK'],
            ['name' => 'CSI ENDENGUE',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI FAEKELE',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de MBALMAYO 1'],
            ['name' => 'CSI MEBOMEZOA',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de OSSOESSAM'],
            ['name' => 'CSI MENGUEME',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de MENGUEME'],
            ['name' => 'CSI MENGUEME BANE',                                'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI MINLABA',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de MINLABA'],
            ['name' => 'CSI NGALLAN',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI NGOANTET',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de METET'],
            ['name' => 'CSI NKOLBEWA',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI NKOLMEYANG',                                   'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de NKOLMEYANG'],
            ['name' => 'CSI NKOLNYAMA',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de NKOLNYAMA'],
            ['name' => 'CSI OBOUT',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI OLAMA',                                        'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de OLAMA'],
            ['name' => 'CSI ONANAMBESSA',                                  'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de ONANAMBESSA'],
            ['name' => 'CSI OSSOESSAM',                                    'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI U MBYO 1',                                     'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'CSI U MBYO2',                                      'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6'],
            ['name' => 'INFIRMERIE PRISON',                                'type' => 'health_center', 'ownership' => 'public',     'region' => 'Centre',        'division' => 'District de Santé de Mbalmayo',   'city' => 'Mbalmayo',   'accreditation_level' => 'Catégorie 6', 'address' => 'Aire de Santé de MBALMAYO 2'],
        ];
    }
}
