@extends('layouts.portal')

@section('title', 'Outbreak Signals')

@section('sidebar_role_badge')
<div class="sidebar-role-badge">
    <i data-lucide="heart-handshake"></i>
    Health Org
</div>
@endsection
@section('sidebar_user_role', 'Health Org Admin')

@section('sidebar_nav')
@include('portals.healthorg._sidebar')
@endsection

@section('breadcrumb_home', 'Health Org Portal')
@section('breadcrumb_home_url', route('portals.healthorg.dashboard'))
@section('breadcrumb_section', 'Outbreak Signals')

@section('content')

<div class="page-header">
    <div>
        <h1 class="page-title">Outbreak & Anomaly Signals</h1>
        <p class="page-subtitle">Disease intelligence and automated anomaly detection signals.</p>
    </div>
</div>

@if($signals->isEmpty())
<div class="alert alert-info">
    <i data-lucide="info"></i>
    <div>
        Outbreak signals are generated by the disease surveillance engine via
        <code class="mono">POST /api/v1/public-health/signals/trigger-detection</code>.
        No signals have been raised yet.
    </div>
</div>
@else
<div class="panel">
    <div class="table-wrapper">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Signal</th>
                    <th>Severity</th>
                    <th>Status</th>
                    <th>Detected</th>
                </tr>
            </thead>
            <tbody>
                @foreach($signals as $signal)
                <tr>
                    <td data-label="Signal"><span class="td-strong">{{ $signal->title ?? $signal->id }}</span></td>
                    <td data-label="Severity">
                        <span class="badge badge-{{ match($signal->severity ?? '') { 'critical' => 'danger', 'high' => 'warning', default => 'neutral' } }}">
                            {{ ucfirst($signal->severity ?? '—') }}
                        </span>
                    </td>
                    <td data-label="Status">
                        <span class="badge badge-{{ match($signal->status ?? '') { 'confirmed' => 'danger', 'under_review' => 'warning', 'resolved' => 'success', default => 'neutral' } }}">
                            {{ ucfirst(str_replace('_', ' ', $signal->status ?? '—')) }}
                        </span>
                    </td>
                    <td data-label="Detected"><span class="td-muted">{{ isset($signal->created_at) ? \Carbon\Carbon::parse($signal->created_at)->format('d M Y H:i') : '—' }}</span></td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endif

@endsection
