@extends('layouts.portal')

@section('title', 'Outbreak Signals')

@section('sidebar_role_badge')
<div class="sidebar-role-badge" style="background:rgba(245,158,11,.15);border-color:rgba(245,158,11,.4);color:#fbbf24;">
    <i data-lucide="heart-handshake" style="width:.75rem;height:.75rem;display:inline;vertical-align:middle;margin-right:4px;"></i>
    Health Org
</div>
@endsection
@section('sidebar_user_role', 'Health Org Admin')

@section('sidebar_nav')
@include('portals.healthorg._sidebar')
@endsection

@section('breadcrumb_home', 'Health Org Portal')
@section('breadcrumb_home_url', route('portals.healthorg.dashboard'))
@section('breadcrumb_section', 'Outbreak Signals')

@section('content')

<div class="page-header">
    <div>
        <h1 class="page-title">Outbreak & Anomaly Signals</h1>
        <p class="page-subtitle">Disease intelligence and automated anomaly detection signals.</p>
    </div>
</div>

@if($signals->isEmpty())
<div class="auth-alert" style="background:#eff6ff;border:1px solid #bfdbfe;color:#1e40af;">
    <i data-lucide="info"></i>
    <div>
        Outbreak signals are generated by the disease surveillance engine via
        <code>POST /api/v1/public-health/signals/trigger-detection</code>.
        No signals have been raised yet.
    </div>
</div>
@else
<div class="card" style="overflow:hidden;">
    <div class="card-body" style="padding:0;overflow-x:auto;">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Signal</th>
                    <th>Severity</th>
                    <th>Status</th>
                    <th>Detected</th>
                </tr>
            </thead>
            <tbody>
                @foreach($signals as $signal)
                <tr>
                    <td style="font-weight:600;">{{ $signal->title ?? $signal->id }}</td>
                    <td>
                        <span class="badge badge-{{ match($signal->severity ?? '') { 'critical' => 'danger', 'high' => 'warning', default => 'default' } }}">
                            {{ ucfirst($signal->severity ?? '—') }}
                        </span>
                    </td>
                    <td>
                        <span class="badge badge-{{ match($signal->status ?? '') { 'confirmed' => 'danger', 'under_review' => 'warning', 'resolved' => 'success', default => 'default' } }}">
                            {{ ucfirst(str_replace('_', ' ', $signal->status ?? '—')) }}
                        </span>
                    </td>
                    <td style="font-size:.83rem;color:#64748b;">
                        {{ isset($signal->created_at) ? \Carbon\Carbon::parse($signal->created_at)->format('d M Y H:i') : '—' }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endif

@endsection
