<?php

namespace Tests\Feature\Architecture;

use Illuminate\Support\Facades\Route;
use Tests\TestCase;

/**
 * Contract guardrail for public/openapi.json (generated by
 * `php artisan opescare:generate-openapi` from the live route table).
 *
 * Enforces the spec is in sync with the routes, BOTH directions:
 *   - no phantom: every documented operation resolves to a real route;
 *   - no gaps: every real api/.well-known route is documented.
 *
 * A route added/removed without regenerating fails this test, which keeps the
 * published spec at 100% coverage and never drifting.
 */
class OpenApiContractTest extends TestCase
{
    private const HTTP_VERBS = ['get', 'post', 'put', 'patch', 'delete'];

    private function normalize(string $path): string
    {
        return preg_replace('/\{[^}]+\}/', '{}', '/' . ltrim($path, '/'));
    }

    /** @return array<string, true> "METHOD /norm/path" => true */
    private function documented(): array
    {
        $raw = file_get_contents(public_path('openapi.json'));
        $spec = json_decode($raw, true);
        $this->assertIsArray($spec, 'public/openapi.json must be valid JSON.');
        $this->assertSame('3.1.0', $spec['openapi'] ?? null, 'openapi version must be 3.1.0.');
        $this->assertArrayHasKey('components', $spec);

        $out = [];
        foreach (($spec['paths'] ?? []) as $path => $ops) {
            foreach ($ops as $verb => $op) {
                if (in_array($verb, self::HTTP_VERBS, true)) {
                    $out[strtoupper($verb) . ' ' . $this->normalize($path)] = true;
                }
            }
        }
        return $out;
    }

    /** @return array<string, true> */
    private function realRoutes(): array
    {
        $out = [];
        foreach (Route::getRoutes()->getRoutes() as $route) {
            $uri = $route->uri();
            if (! str_starts_with($uri, 'api/') && ! str_starts_with($uri, '.well-known/')) {
                continue;
            }
            foreach ($route->methods() as $m) {
                if (in_array($m, ['HEAD', 'OPTIONS'], true)) {
                    continue;
                }
                $out[strtoupper($m) . ' ' . $this->normalize('/' . $uri)] = true;
            }
        }
        return $out;
    }

    public function test_no_phantom_operations(): void
    {
        $phantom = array_keys(array_diff_key($this->documented(), $this->realRoutes()));
        sort($phantom);
        $this->assertSame(
            [],
            $phantom,
            "openapi.json documents operations that are not real routes:\n  " . implode("\n  ", $phantom)
        );
    }

    public function test_spec_is_in_sync_with_routes(): void
    {
        $documented = $this->documented();
        $missing = array_keys(array_diff_key($this->realRoutes(), $documented));
        sort($missing);
        $this->assertSame(
            [],
            $missing,
            count($missing) . " api/.well-known routes are missing from openapi.json. "
            . "Run `php artisan opescare:generate-openapi` and commit the result.\n  "
            . implode("\n  ", array_slice($missing, 0, 40))
        );
        fwrite(STDERR, sprintf("[openapi] %d operations documented — 100%% of the live route table\n", count($documented)));
    }
}
